name: 'Cross Env E2E Tests'
#https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the tests against'
        required: true
        type: environment
        default: dev
        
jobs:
  option-example:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "input environment selected -> ${{ github.event.inputs.environment }}"

  pre-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x    

      - name: Install dependencies
        run: npm ci

      - name: Check ESLint 
        run: npx eslint ./cypress --ext .js


  e2e-tests:
    needs: pre-check
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001

    steps:
      - name: read a variable
        run: echo "The USER is $USER and the base url is $BASE_URL_WEB and $TEST"
        env:
          USER:  ${{ vars.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL_WEB: ${{ vars.BASE_URL_WEB }} 
          BASE_URL_API: ${{ vars.BASE_URL_API }}
  
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Cypress run api tests
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --browser chrome --headless --quiet --spec 'cypress/e2e/UI-tests/log-tests.spec.cy.js' --env allure=true'
        env:
          USER:  ${{ vars.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BASE_URL_WEB: ${{ vars.BASE_URL_WEB }} 
          BASE_URL_API: ${{ vars.BASE_URL_API }}

      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean
          npx allure open